### ISSUE TITLE
Negative prob value in ML

### ISSUE THREAD

**Issue by weiway** [almlab/adaptml-angst-server#1]
Program will break occasionally because of negative prob value in line 307 ML.py while running Adaptml.py.

I can provide more details of this error and the input newick tree causing this problem.

**Comment by albertyw** [comment]
@weiway can you please move this issue to https://github.com/ladavid/adaptml?  This repository is specific to the wrappers around AdaptML and AnGST that allow it to be run online.

**Comment by weiway** [comment]
No problem, thank you!
